modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="soultrap" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Soul Trap" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/soul-trap-forge" #optional
logoFile="icon.png" #optional
authors="Favouriteless" #optional
description='''
A mod to allow you to create your own spawners in a balanced, vanilla styled way.
'''

# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
